version: '3'

services:
  webpack:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    ports:
      - "8080:8080"
    command: "npm run dev"