version: '3'

services:
  webpack:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    volumes:
      - ./src:/app/src
    ports:
      - "3002:3002"
    command: "npm run dev"